version: '3.3'

services:
  images:
    container_name: images
    image: nginx
    restart: always
    networks:
      - traefik_network
    volumes:
      - ./www/:/images
      - ./vhosts/prod:/etc/nginx/conf.d
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.http.routers.images.rule=Host(`images.gainsbourg.net`)
      - traefik.http.routers.images.entrypoints=websecure
      - traefik.http.routers.images.tls=true
      - traefik.http.routers.images.tls.certresolver=myresolver

networks:
  traefik_network:
    external: true
